# Generated by Django 2.2.6 on 2021-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Если мысли не передать словами (необязательно)', null=True, upload_to='posts/', verbose_name='Прикрепить картинку'),
        ),
    ]
